# Generated by Django 4.0.2 on 2022-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
